[package]
name = "cancellation-token"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
parking_lot = "0.12.1"

[dev-dependencies]
futures-test = "0.3.30"
assert_matches = "1.5.0"
